### entities ###
GET {{baseurl}}/{{tenantId}}/{{environment}}/{{api}}
Authorization: Basic {{username}} {{password}} 

### metadata ###
GET {{baseurl}}/{{tenantId}}/{{environment}}/{{api}}/$metadata
Authorization: Basic {{username}} {{password}} 


### All companies ###
# @name allCompanies
GET {{baseurl}}/{{tenantId}}/{{environment}}/{{api}}/companies
Authorization: Basic {{username}} {{password}} 

###

### Get CompanyId ###
# @name getCompanyid
GET {{baseurl}}/{{tenantId}}/{{environment}}/{{api}}/companies?$filter=name eq 'My Company' 
Authorization: Basic {{username}} {{password}} 

### 
@cid = {{getCompanyid.response.body.value[0].id}}

###
### customers ###

GET {{baseurl}}/{{tenantId}}/{{environment}}/{{api}}/companies({{cid}})/customers
Authorization: Basic {{username}} {{password}} 

###

### salesOrderLine ###
# @name salesOrderLine
GET {{baseurl}}/{{tenantId}}/{{environment}}/{{api}}/companies({{cid}})/salesOrderLines?$filter= id eq 'f7800ab3-5f90-ea11-a812-000d3ae6aa98-10000'
Authorization: Basic {{username}} {{password}} 

###

### shipmentMethods ###
# @name shipmentMethods
GET {{baseurl}}/{{tenantId}}/{{environment}}/{{api}}/companies({{cid}})/shipmentMethods
Authorization: Basic {{username}} {{password}} 

###

### salesOrders ###
# @name salesOrders
GET {{baseurl}}/{{tenantId}}/{{environment}}/{{api}}/companies({{cid}})/salesOrders
Authorization: Basic {{username}} {{password}} 

###

### dimensions ###
# @name dimensions
GET {{baseurl}}/{{tenantId}}/{{environment}}/{{api}}/companies({{cid}})/dimensionSetLine?$filter= valueId eq e4b66288-f84e-ea11-bb34-000d3a255781
Authorization: Basic {{username}} {{password}} 

###
//customers(fc9f7ff8-9e1a-ea11-a813-000d3a560b8f)/defaultDimensions
###

### dimensionValues ###
# @name dimensionValues
GET {{baseurl}}/{{tenantId}}/{{environment}}/{{api}}/companies({{cid}})/dimensionValues
Authorization: Basic {{username}} {{password}} 

###

### dimensionLines ###
# @name dimensionLines
GET {{baseurl}}/{{tenantId}}/{{environment}}/{{api}}/companies({{cid}})/(627bb355-9dfa-49d9-bfb2-4a7e0dbe93b7)/dimensionSetLines  
Authorization: Basic {{username}} {{password}} 

###
//(627bb355-9dfa-49d9-bfb2-4a7e0dbe93b7)
### subscriptions ###
# @name subscriptions
GET {{baseurl}}/{{tenantId}}/{{environment}}/api/microsoft/runtime/beta/companies({{cid}})/webhookSupportedResources
Authorization: Basic {{username}} {{password}} 

###

###  CreateSubscription ###
# @name CreateSubscription
POST  {{baseurl}}/{{tenantId}}/{{environment}}/{{api}}/subscriptions
Authorization: Basic {{username}} {{password}} 
Content-Type: application/json
If-Match: *

{
  "notificationUrl": "{{notificationurl}}",
  "resource":  "{{baseurl}}/{{tenantId}}/{{environment}}/{{api}}}}/companies({{cid}})/customers",
  "clientState": "test" 
}
###
GET https://{businesscentralPrefix}/api/microsoft/runtime/beta/companies({{cid})/webhookSupportedResources?$filter=resource eq 'v1.0*' 
Content-type: application/json

###

get  https://api.businesscentral.dynamics.com/V2.0/92226e37-ba60-4082-93d0-8a400023c938/sandbox/api/V1.0/companies({{cid}})/customers?$expand=defaultDimensions 
Authorization: Basic {{username}} {{password}} 

###

### Custom Entities ###

### inventoryFeed ###
GET {{baseurl}}/{{tenantId}}/{{environment}}/api/{{APIPublisher}}/{{APIGroup}}/{{APIVersion}}/companies({{cid}})/inventoryFeed
Authorization: Basic {{username}} {{password}} 


